name: "build application"

on:
  push:
    branches:
      - main

jobs:
  build-application:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        name: setup-java
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: run test
        run: ./mvnw test
